# Generated by Django 5.1.3 on 2024-12-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
