# Generated by Django 5.1.3 on 2024-12-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rating_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-date'], 'verbose_name': 'Driver Rating', 'verbose_name_plural': 'Driver Ratings'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(help_text='Detailed comment about the driver', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Date when the rating was given', verbose_name='Date of Rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='driver',
            field=models.CharField(help_text='Unique identifier for the driver', max_length=20, verbose_name='Driver ID'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.CharField(default='Anonymous', help_text='Name of the person giving the rating', max_length=50, verbose_name='Reviewer Name'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, help_text='Rating score from 0 to 5', verbose_name='Rating Score'),
        ),
    ]
