# Generated by Django 5.1.3 on 2024-12-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_rating_options_alter_rating_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='email',
            field=models.EmailField(default='', help_text='Email of the person giving the rating', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='rating',
            name='emailme',
            field=models.BooleanField(default=False, help_text='Send me an email when a new driver is released so I can update and rate it', verbose_name='Email Me'),
        ),
    ]
