# Generated by Django 5.1.3 on 2024-12-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rating_email_rating_emailme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='emailme',
        ),
        migrations.AlterField(
            model_name='rating',
            name='email',
            field=models.EmailField(default='', help_text='Add your email if you want to be notified of new driver releases, so you can update and rate the new driver', max_length=254, verbose_name='Email'),
        ),
    ]
