# Generated by Django 5.1.3 on 2024-12-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_rating_emailme_alter_rating_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='distro',
            field=models.CharField(default='', help_text='Linux distribution used by the reviewer', max_length=50, verbose_name='Linux Distro'),
        ),
    ]
